sudo: required
services:
  - docker

before_install:
   - docker build -t pavanakartikvelagaleti/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pavanakartikvelagaleti/react-test npm test
after_success:
  - docker build -t pavanakartikvelagaleti/multi-client ./client
  - docker build -t pavanakartikvelagaleti/multi-nginx ./nginx
  - docker build -t pavanakartikvelagaleti/multi-server ./server
  - docker build -t pavanakartikvelagaleti/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pavanakartikvelagaleti/multi-client
  - docker push pavanakartikvelagaleti/multi-nginx
  - docker push pavanakartikvelagaleti/multi-server
  - docker push pavanakartikvelagaleti/multi-worker


deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucker_name: "elasticbeanstalk-us-east-2-685819197856"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"


